### ISSUE TITLE
Is it possible for the pyanoh3ro to generate the pitch rectangles from other midi files beside the files attached to the code?

### ISSUE THREAD

**Issue by poiler22** [lowagner/pyanoh3ro#2]

**Comment by poiler22** [comment]
I would like to implement your code to my practice; however, when I tried to use the other midi files, putting them in the songs directory, only sound is play, no shape of rectangles.

**Comment by lowagner** [comment]
i am super impressed i'm getting pings on this after so many years.  IIRC, standard midi files don't seem to put anything on track zero, and that's the default track that is shown in edit mode.  so if you don't see the notes it is because they live on a different track (if you are hearing them, that means they do exist somewhere), and you can get to a new track using the command "e X" where X is the other track.

https://github.com/lowagner/pyanoh3ro/blob/master/edit.py#L133

in play mode, i believe you can choose which track you want to practice, and the other tracks are automatically added for you.  (IIRC)
